/*
Titlul proiectului: Educație și dezvoltare în era digitală
Cod proiect: POCU/860/3/12/143072 
Curs: Introducere în analiza datelor de mari dimensiuni
Perioada: mai-iunie 2023 
*/

-- Script pentru crearea popularea tabelei COUNTRY_GEN_INFO din baza de date COVID. Sintaxa PostgreSQL


INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AFG', 'Afghanistan', 'South Asia', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ALB', 'Albania', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DZA', 'Algeria', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AND', 'Andorra', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AGO', 'Angola', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ATG', 'Antigua and Barbuda', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ARG', 'Argentina', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ARM', 'Armenia', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AUS', 'Australia', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AUT', 'Austria', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('AZE', 'Azerbaijan', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BHS', 'Bahamas, The', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BHR', 'Bahrain', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BGD', 'Bangladesh', 'South Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BRB', 'Barbados', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BLR', 'Belarus', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BEL', 'Belgium', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BLZ', 'Belize', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BEN', 'Benin', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BTN', 'Bhutan', 'South Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BOL', 'Bolivia', 'Latin America and  Caribbean', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BIH', 'Bosnia and Herzegovina', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BWA', 'Botswana', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BRA', 'Brazil', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BRN', 'Brunei Darussalam', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BGR', 'Bulgaria', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BFA', 'Burkina Faso', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('BDI', 'Burundi', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CPV', 'Cabo Verde', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KHM', 'Cambodia', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CMR', 'Cameroon', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CAN', 'Canada', 'North America', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CAF', 'Central African Republic', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TCD', 'Chad', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CHL', 'Chile', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CHN', 'China', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('COL', 'Colombia', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('COM', 'Comoros', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('COG', 'Congo, Rep.', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CRI', 'Costa Rica', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('HRV', 'Croatia', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CUB', 'Cuba', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CYP', 'Cyprus', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CZE', 'Czech Republic', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CIV', 'Cote d''Ivoire', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PRK', 'Korea, Dem. People’s Rep.', 'East Asia and  Pacific', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('COD', 'Congo, Dem. Rep.', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DNK', 'Denmark', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DJI', 'Djibouti', 'Middle East and  North Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DMA', 'Dominica', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DOM', 'Dominican Republic', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ECU', 'Ecuador', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('EGY', 'Egypt, Arab Rep.', 'Middle East and  North Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SLV', 'El Salvador', 'Latin America and  Caribbean', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GNQ', 'Equatorial Guinea', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ERI', 'Eritrea', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('EST', 'Estonia', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ETH', 'Ethiopia', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('FJI', 'Fiji', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('FIN', 'Finland', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('FRA', 'France', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GAB', 'Gabon', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GMB', 'Gambia, The', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GEO', 'Georgia', 'Europe and  Central Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('DEU', 'Germany', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GHA', 'Ghana', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GRC', 'Greece', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GRD', 'Grenada', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GTM', 'Guatemala', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GIN', 'Guinea', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GNB', 'Guinea-Bissau', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GUY', 'Guyana', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('HTI', 'Haiti', 'Latin America and  Caribbean', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('HND', 'Honduras', 'Latin America and  Caribbean', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('HUN', 'Hungary', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ISL', 'Iceland', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('IND', 'India', 'South Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('IDN', 'Indonesia', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('IRN', 'Iran, Islamic Rep.', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('IRQ', 'Iraq', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('IRL', 'Ireland', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ISR', 'Israel', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ITA', 'Italy', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('JAM', 'Jamaica', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('JPN', 'Japan', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('JOR', 'Jordan', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KAZ', 'Kazakhstan', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KEN', 'Kenya', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KIR', 'Kiribati', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KWT', 'Kuwait', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KGZ', 'Kyrgyz Republic', 'Europe and  Central Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LAO', 'Lao PDR', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LVA', 'Latvia', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LBN', 'Lebanon', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LSO', 'Lesotho', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LBR', 'Liberia', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LBY', 'Libya', 'Middle East and  North Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LTU', 'Lithuania', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LUX', 'Luxembourg', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MDG', 'Madagascar', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MWI', 'Malawi', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MYS', 'Malaysia', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MDV', 'Maldives', 'South Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MLI', 'Mali', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MLT', 'Malta', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MRT', 'Mauritania', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MUS', 'Mauritius', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MEX', 'Mexico', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('FSM', 'Micronesia, Fed. Sts.', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MNG', 'Mongolia', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MNE', 'Montenegro', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MAR', 'Morocco', 'Middle East and  North Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MOZ', 'Mozambique', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MMR', 'Myanmar', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NAM', 'Namibia', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NRU', 'Nauru', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NPL', 'Nepal', 'South Asia', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NLD', 'Netherlands', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NZL', 'New Zealand', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NIC', 'Nicaragua', 'Latin America and  Caribbean', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NER', 'Niger', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NGA', 'Nigeria', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('NOR', 'Norway', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('OMN', 'Oman', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PAK', 'Pakistan', 'South Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PAN', 'Panama', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PNG', 'Papua New Guinea', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PRY', 'Paraguay', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PER', 'Peru', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PHL', 'Philippines', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('POL', 'Poland', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('PRT', 'Portugal', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('QAT', 'Qatar', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KOR', 'Korea, Rep.', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MDA', 'Moldova', 'Europe and  Central Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ROU', 'Romania', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('RUS', 'Russian Federation', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('RWA', 'Rwanda', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('KNA', 'St. Kitts and Nevis', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LCA', 'St. Lucia', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('VCT', 'St. Vincent and the Grenadines', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('WSM', 'Samoa', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('STP', 'Sao Tome and Principe', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SAU', 'Saudi Arabia', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SEN', 'Senegal', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SRB', 'Serbia', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SYC', 'Seychelles', 'Sub-Saharan Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SLE', 'Sierra Leone', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SGP', 'Singapore', 'East Asia and  Pacific', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SVK', 'Slovak Republic', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SVN', 'Slovenia', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SLB', 'Solomon Islands', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SOM', 'Somalia', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ZAF', 'South Africa', 'Sub-Saharan Africa', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ESP', 'Spain', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('LKA', 'Sri Lanka', 'South Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SDN', 'Sudan', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SUR', 'Suriname', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SWZ', 'Eswatini', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SWE', 'Sweden', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('CHE', 'Switzerland', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('SYR', 'Syrian Arab Republic', 'Middle East and  North Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TJK', 'Tajikistan', 'Europe and  Central Asia', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('THA', 'Thailand', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('MKD', 'Macedonia, FYR', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TLS', 'Timor-Leste', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TGO', 'Togo', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TON', 'Tonga', 'East Asia and  Pacific', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TTO', 'Trinidad and Tobago', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TUN', 'Tunisia', 'Middle East and  North Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TUR', 'Turkey', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TKM', 'Turkmenistan', 'Europe and  Central Asia', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('UGA', 'Uganda', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('UKR', 'Ukraine', 'Europe and  Central Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ARE', 'United Arab Emirates', 'Middle East and  North Africa', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('GBR', 'United Kingdom', 'Europe and  Central Asia', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('TZA', 'Tanzania', 'Sub-Saharan Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('USA', 'United States', 'North America', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('URY', 'Uruguay', 'Latin America and  Caribbean', 'High income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('UZB', 'Uzbekistan', 'Europe and  Central Asia', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('VUT', 'Vanuatu', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('VEN', 'Venezuela, RB', 'Latin America and  Caribbean', 'Upper middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('VNM', 'Vietnam', 'East Asia and  Pacific', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('YEM', 'Yemen, Rep.', 'Middle East and  North Africa', 'Low income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ZMB', 'Zambia', 'Sub-Saharan Africa', 'Lower middle income');
INSERT INTO COUNTRY_GEN_INFO (COUNTRY_CODE, COUNTRY_NAME, REGION, COUNTRY_INCOME_GROUP) 
VALUES ('ZWE', 'Zimbabwe', 'Sub-Saharan Africa', 'Low income');
